### PR TITLE
support for text_color in tags

### PR DESCRIPTION
**Pull request by alon-sht**

### CODE REVIEW

**Comment by arnaudmiribel** [comment]
Hey @alon-sht, thanks for the PR. I'm working on fixing the CI failing in https://github.com/arnaudmiribel/streamlit-extras/pull/250

**Comment by arnaudmiribel** [comment]
@alon-sht please pull from main after https://github.com/arnaudmiribel/streamlit-extras/pull/250 was merged - this should solve the deploy issue

**Comment by alon-sht** [comment]
Please take a look now :)

**Comment by arnaudmiribel** [comment]
@alon-sht would you mind making sure the linting is right? We use `pre-commit`, hopefully you're familiar with that.

tl;dr:
```
pip install pre-commit
pre-commit install
pre-commit run --all
```

**Comment by alon-sht** [comment]
It's new to me
I've ran pre-commit and fixed a bug

**Comment by arnaudmiribel** [comment]
Well done fixing the linting issues with pre-commit. Looks like there are still errors running the test: see 

By the way, wanted to call out Streamlit now has nice native way to make tags if you're interested - see colored text [in docs](https://docs.streamlit.io/develop/api-reference/text/st.markdown). 

image

**Comment by alon-sht** [comment]
I tried adding another fix
I'm currently having trouble running pytest in my IDE for some reason.

**Comment by alon-sht** [comment]
Streamlit's native way is nice, but your implementation is prettier and more versatile in terms of color options :)

**Comment by alon-sht** [comment]
Latest commit passed all tests

**Review by arnaudmiribel — APPROVED** [review]
Well done! Let's merge this 👏 @alon-sht

**Pull request merged**
