### PR TITLE
Add button selector

### PR DESCRIPTION
**Pull request by daxmu92**

### CODE REVIEW

**Comment by arnaudmiribel** [comment]
Hey @daxmu92, this is a lovely contribution! Thanks a lot. Some feedback:
1. Did you run `pre-commit` on your branch to make sure the linting is done right? (see the  `pip install pre-commit && pre-commit run --all` should do! Looks like the [test is failing](https://github.com/arnaudmiribel/streamlit-extras/actions/runs/11211860551/job/31164727988), it seems to not be related to you though, I'll have a look.
2. Can you please update the arguments so they are more consistent with existing arguments found in Streamlit native commands? I think that will be helpful for developers to understand how to use your extra. Let me know what you think. Here are some suggestions:
CleanShot 2024-10-07 at 11 58 55@2x

**Comment by daxmu92** [comment]
@arnaudmiribel Thanks for you kindly reply! I have fixed most of them and the cicd shows passed. 

However, in the generated deploy-preview, it can't find my extra:
> ModuleNotFoundError: No module named 'streamlit_extras.button_selector'

Did I miss anything?

**Comment by arnaudmiribel** [comment]
Hey @daxmu92, thank you so much for the changes! There seems to be an issue remaining with pre-commit but that nothing do to with your code, I ran the pre-commit on your branch and it seemed to work fine.

As for the ModuleNotFoundError in the `Output (beta)` container of the preview docs, it is an expected limitation. In fact, the documentation builds off the branch code (that's why we can see your contribution in there!) but [stlite](https://github.com/whitphx/stlite), the technology that's used to render the code snippet, can't build `streamlit_extras` from the branch source, and instead relies on the latest available version that's on PyPI, which obviously doesn't include your extra, yet!  Upon releasing a new version in PyPI, that part should work though!

**Comment by daxmu92** [comment]
Thanks! Let me know if you have other concerns.

**Comment by arnaudmiribel** [comment]
Opened #255 that should be merged (and this branch should pull after that) - which should fix the linting CI failing

**Comment by arnaudmiribel** [comment]
@daxmu92 can you pull from main? Should resolve the issue

**Pull request merged**
