### PR TITLE
Fix issue with vertical alignment for grid

### PR DESCRIPTION
**Pull request by LukasMasuch**
This PR fixes an issue with the row & grid extras with the most recent version of Streamlit. The vertical alignment didn't work correctly anymore with those versions.

Closes https://github.com/arnaudmiribel/streamlit-extras/issues/201

### CODE REVIEW

**Review by arnaudmiribel — APPROVED** [review]
Thanks @LukasMasuch!

**Comment by arnaudmiribel** [comment]
You might as well add a version bump so we release that along!

**Comment by LukasMasuch** [comment]
@arnaudmiribel Oki, i bumped it to 0.3.6. But not sure if I did it correctly? I just manually updated the `projects.toml`.

**Review by arnaudmiribel — APPROVED** [review]
Yep ,all grea! Thanks @LukasMasuch

**Pull request merged**
