### PR TITLE
Created CONTRIBUTING with emojis

### PR DESCRIPTION
**Pull request by Nishu0**
- Easy to navigate Contributing Guideline in Github Only 
- Added emojis to Contributing Guideline

### CODE REVIEW

**Comment by blackary** [comment]
Hi @Nishu0, thanks for this -- great addition! Would you mind also updating the docs/contributions.md so that it's a symlink to this file, so we don't have the (essentially) same content twice?

If you're in the docs folder, you can do `ln -s ../CONTRIBUTING.md contributing.md`, like this https://github.com/arnaudmiribel/streamlit-extras/pull/194

**Comment by Nishu0** [comment]
@blackary 

Thanks for the review and I will update docs/contributions.md and do the necessary changes.

**Comment by Nishu0** [comment]
@blackary I have made the necessary changes. Let me know if any other changes are required. And thanks for the Review.

**Review by arnaudmiribel — APPROVED** [review]
Thanks @Nishu0 for your help making this contribution guide nicer!

**Pull request merged**
